In [1]:
%load_ext autoreload
%autoreload 2

from GPTDatasetV1 import GPTDatasetV1
import tiktoken
import torch

In [2]:
tokenizer = tiktoken.get_encoding("gpt2")
text = (
 "Hello, do you like tea? <|endoftext|> In the sunlit terraces"
 "of someunknownPlace."
)
integers = tokenizer.encode(text, allowed_special={"<|endoftext|>"})
print(integers)
strings = tokenizer.decode(integers)
print(strings)

[15496, 11, 466, 345, 588, 8887, 30, 220, 50256, 554, 262, 4252, 18250, 8812, 2114, 1659, 617, 34680, 27271, 13]
Hello, do you like tea? <|endoftext|> In the sunlit terracesof someunknownPlace.


In [3]:
with open("the-verdict.txt", "r", encoding="utf-8") as f:
 raw_text = f.read()


enc_text = tokenizer.encode(raw_text)
print(len(enc_text))



5145


In [4]:
enc_sample = enc_text[50:]
enc_sample

[290,
 4920,
 2241,
 287,
 257,
 4489,
 64,
 319,
 262,
 34686,
 41976,
 13,
 357,
 10915,
 314,
 2138,
 1807,
 340,
 561,
 423,
 587,
 10598,
 393,
 28537,
 2014,
 198,
 198,
 1,
 464,
 6001,
 286,
 465,
 13476,
 1,
 438,
 5562,
 373,
 644,
 262,
 1466,
 1444,
 340,
 13,
 314,
 460,
 3285,
 9074,
 13,
 46606,
 536,
 5469,
 438,
 14363,
 938,
 4842,
 1650,
 353,
 438,
 2934,
 489,
 3255,
 465,
 48422,
 540,
 450,
 67,
 3299,
 13,
 366,
 5189,
 1781,
 340,
 338,
 1016,
 284,
 3758,
 262,
 1988,
 286,
 616,
 4286,
 705,
 1014,
 510,
 26,
 475,
 314,
 836,
 470,
 892,
 286,
 326,
 11,
 1770,
 13,
 8759,
 2763,
 438,
 1169,
 2994,
 284,
 943,
 17034,
 318,
 477,
 314,
 892,
 286,
 526,
 383,
 1573,
 11,
 319,
 9074,
 13,
 536,
 5469,
 338,
 11914,
 11,
 33096,
 663,
 4808,
 3808,
 62,
 355,
 996,
 484,
 547,
 12548,
 287,
 281,
 13079,
 410,
 12523,
 286,
 22353,
 13,
 843,
 340,
 373,
 407,
 691,
 262,
 9074,
 13,
 536,
 48819,
 508,
 25722,
 276,
 13,
 11161,
 407,
 262,
 40123,
 18113,


In [5]:
context_size = 4
for i in range(1, context_size + 1):
    context = enc_sample[:i]
    desired = enc_sample[i]
    print(f"Context: {context}. Desired: {desired}")

Context: [290]. Desired: 4920
Context: [290, 4920]. Desired: 2241
Context: [290, 4920, 2241]. Desired: 287
Context: [290, 4920, 2241, 287]. Desired: 257


In [6]:
vocab_size = tokenizer.n_vocab
output_dim = 256 # can choose this to be whatever
max_length = 4
context_length = max_length

token_embedding_layer = torch.nn.Embedding(vocab_size, output_dim)
pos_embedding_layer = torch.nn.Embedding(context_length, output_dim)


dataloader = GPTDatasetV1.create_dataloader(raw_text, batch_size=8, shuffle=False, stride=max_length, max_length=max_length)
data_iter = iter(dataloader)
inputs, targets = next(data_iter)
print(f"Token IDs: {inputs}.\nInputs shape: {inputs.shape}")
print(f"Target IDs: {targets}.\nTargets shape: {targets.shape}")

token_embeddings = token_embedding_layer(inputs)
pos_embeddings = pos_embedding_layer(torch.arange(context_length))
input_embeddings = token_embeddings + pos_embeddings
print(f"Token embedding shape: {token_embeddings.shape}")
print(f"Positional embedding shape: {pos_embeddings.shape}")
print(f"Final embedding shape: {input_embeddings.shape}")

Token IDs: tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]]).
Inputs shape: torch.Size([8, 4])
Target IDs: tensor([[  367,  2885,  1464,  1807],
        [ 3619,   402,   271, 10899],
        [ 2138,   257,  7026, 15632],
        [  438,  2016,   257,   922],
        [ 5891,  1576,   438,   568],
        [  340,   373,   645,  1049],
        [ 5975,   284,   502,   284],
        [ 3285,   326,    11,   287]]).
Targets shape: torch.Size([8, 4])
Token embedding shape: torch.Size([8, 4, 256])
Positional embedding shape: torch.Size([4, 256])
Final embedding shape: torch.Size([8, 4, 256])


In [57]:
from custom_modules import Linear, Embedding, RMSNorm, softmax

In [54]:
d_model = 10

emb = Embedding(7, 10)

In [56]:
for p in emb.parameters():
    print(p)

indices = torch.tensor([[0, 1, 2], [2, 5, 6]])

embs = emb(indices)
print(embs.shape)

embs

Parameter containing:
tensor([[ 1.0290, -0.6574,  0.9376,  0.1349, -0.3423,  0.1368, -0.0433,  0.7723,
          0.9200,  1.0290],
        [-0.0331,  0.2743, -0.5023,  0.8759, -0.4223, -0.1321,  0.2855, -1.0290,
         -0.6581,  0.3911],
        [-0.8819,  1.0290, -1.0290,  0.6588, -1.0290,  0.4543, -1.0290,  1.0290,
          0.5902, -0.8397],
        [ 0.8440,  0.4246,  0.4644,  0.2706,  0.0091, -1.0290,  1.0290, -0.2622,
         -0.4488,  0.4660],
        [-0.7050,  0.9599,  0.5599, -0.0822,  0.8949, -0.4003,  0.0100,  0.2844,
          0.8587, -0.2806],
        [ 0.6653,  1.0290, -0.6511, -0.0045, -0.1877, -1.0290,  1.0290, -0.1793,
          0.5620, -0.0076],
        [-0.4028, -0.1037, -0.6887,  0.3117, -0.0706,  0.0137,  0.7109,  0.5689,
          0.9654,  0.4305]], requires_grad=True)
torch.Size([2, 3, 10])


tensor([[[ 1.0290, -0.6574,  0.9376,  0.1349, -0.3423,  0.1368, -0.0433,
           0.7723,  0.9200,  1.0290],
         [-0.0331,  0.2743, -0.5023,  0.8759, -0.4223, -0.1321,  0.2855,
          -1.0290, -0.6581,  0.3911],
         [-0.8819,  1.0290, -1.0290,  0.6588, -1.0290,  0.4543, -1.0290,
           1.0290,  0.5902, -0.8397]],

        [[-0.8819,  1.0290, -1.0290,  0.6588, -1.0290,  0.4543, -1.0290,
           1.0290,  0.5902, -0.8397],
         [ 0.6653,  1.0290, -0.6511, -0.0045, -0.1877, -1.0290,  1.0290,
          -0.1793,  0.5620, -0.0076],
         [-0.4028, -0.1037, -0.6887,  0.3117, -0.0706,  0.0137,  0.7109,
           0.5689,  0.9654,  0.4305]]], grad_fn=<IndexBackward0>)

In [74]:
test = torch.tensor([[[0, 1, 2], [2, 5, 6]], [[0, 10, 2], [-2, 50, 6]], [[0, 69, 2], [2, 5, 600]]]).to(torch.float32)

left = softmax(test, axis=-1) 
right = torch.softmax(test, dim=-1)

left - right

tensor([[[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 2.9802e-08, 0.0000e+00]],

        [[3.6380e-12, 0.0000e+00, 2.9104e-11],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])